"""update_for_trustedmodel

Revision ID: f9f4ddbf5c7f
Revises: 77b19efadb26
Create Date: 2026-02-15 15:48:59.394304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9f4ddbf5c7f'
down_revision: Union[str, None] = '77b19efadb26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('risk_score', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predictions', 'risk_score')
    # ### end Alembic commands ###
